In [95]:
from keras.models import Sequential
from keras.layers import Dense
import pandas as pd

In [96]:
df = pd.read_csv("train_titanic.csv")

In [97]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             62
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [98]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,7.0,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [99]:
#je supprime la cologne cabin car il y a trop de valeurs manquantes
df.drop("Cabin", axis=1, inplace=True)

In [100]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,7.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [101]:
#afficher les 2 lignes ou il manque embarked
missing_embarked = df[df['Embarked'].isnull()]
print(missing_embarked)

     PassengerId  Survived  Pclass                                       Name  \
61            62         1       1                        Icard, Miss. Amelie
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)

        Sex   Age  SibSp  Parch  Ticket  Fare Embarked
61   female  38.0      0      0  113572  80.0      NaN
829  female  62.0      0      0  113572  80.0      NaN

In [102]:
#Remplir les valeurs manquantes que j'ai trouvÃ© sur : https://titanicfacts.net/titanic-passenger-list/
df.at[61, 'Embarked'] = 'S'

df.at[829, 'Embarked'] = 'S'

In [103]:
df.isnull().sum()

PassengerId     0
Survived        0
Pclass          0
Name            0
Sex             0
Age            62
SibSp           0
Parch           0
Ticket          0
Fare            0
Embarked        0
dtype: int64

In [104]:
#je vais maintenenat ajouter les ages manquantes
missing_age = df[df['Age'].isnull()]
print(missing_age['PassengerId'])

5        6
19      20
26      27
32      33
36      37
      ...
531    532
552    553
697    698
709    710
878    879
Name: PassengerId, Length: 62, dtype: int64

In [105]:
#une fois que j'ai entrÃ© les ages que j'ai trouvÃ© sur le site ceux qui sont introuvable je remplace par la mediane

# Calculer la mÃ©diane des Ã¢ges
median_age = df['Age'].median()

# Remplacer les Ã¢ges manquants par la mÃ©diane
df['Age'].fillna(median_age, inplace=True)

C:\Users\moon\AppData\Local\Temp\ipykernel_6300\1748323731.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(median_age, inplace=True)

In [106]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [107]:
#je supprime la cologne cabin car il y a trop de valeurs manquantes
df.drop("Ticket", axis=1, inplace=True)

In [108]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,S

In [109]:
#je supprime la cologne cabin car il y a trop de valeurs manquantes
df.drop("PassengerId", axis=1, inplace=True)

In [110]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,S
...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,13.0000,S
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,30.0000,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,7.0,1,2,23.4500,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,30.0000,C
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,7.7500,Q

In [111]:
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# SÃ©lectionner les caractÃ©ristiques numÃ©riques et catÃ©gorielles
numeric_features = ['Age', 'Fare']
categorical_features = ['Sex', 'Embarked', 'Parch', 'SibSp', 'Pclass']

# CrÃ©er les transformateurs pour la normalisation et l'encodage
numeric_transformer = Pipeline(steps=[
    ('scaler', MinMaxScaler())])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder())])

# CrÃ©er un preprocessor pour appliquer les transformations Ã  diffÃ©rentes colonnes
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)])

# Appliquer le prÃ©traitement aux donnÃ©es
preprocessed_data = preprocessor.fit_transform(df)

In [112]:
preprocessed_data

<891x24 sparse matrix of type '<class 'numpy.float64'>'
	with 6221 stored elements in Compressed Sparse Row format>

In [113]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [120]:
from sklearn.model_selection import train_test_split

X = preprocessed_data
y = df['Survived']

# Convertir les donnÃ©es X_train et y_train de format csr_matrix en tableaux NumPy
X_train_np = X_train.toarray()
y_train_np = np.array(y_train)

# Division des donnÃ©es en ensembles d'entraÃ®nement et de test
X_train, X_test, y_train, y_test = train_test_split(X_train_np, y_train_np, test_size=0.2, random_state=42)

In [121]:
# CrÃ©ation du modÃ¨le
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dropout(0.5),  # Dropout pour rÃ©duire le surapprentissage
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')  # Couche de sortie avec une seule sortie (classification binaire)
])

# Compilation du modÃ¨le
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Afficher un rÃ©sumÃ© du modÃ¨le
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 64)                1600

 dropout_2 (Dropout)         (None, 64)                0

 dense_7 (Dense)             (None, 32)                2080

 dense_8 (Dense)             (None, 1)                 33

=================================================================
Total params: 3,713
Trainable params: 3,713
Non-trainable params: 0
_________________________________________________________________

In [122]:
import numpy as np

# EntraÃ®nement du modÃ¨le

history = model.fit(X_train, y_train, epochs=200, batch_size=10, validation_split=0.1)

Epoch 1/200
52/52 [==============================] - 1s 7ms/step - loss: 0.6495 - accuracy: 0.6035 - val_loss: 0.5876 - val_accuracy: 0.6140
Epoch 2/200
52/52 [==============================] - 0s 2ms/step - loss: 0.5874 - accuracy: 0.6895 - val_loss: 0.5272 - val_accuracy: 0.7368
Epoch 3/200
52/52 [==============================] - 0s 2ms/step - loss: 0.5263 - accuracy: 0.7539 - val_loss: 0.4598 - val_accuracy: 0.8070
Epoch 4/200
52/52 [==============================] - 0s 2ms/step - loss: 0.5185 - accuracy: 0.7734 - val_loss: 0.4344 - val_accuracy: 0.8246
Epoch 5/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4951 - accuracy: 0.7871 - val_loss: 0.4148 - val_accuracy: 0.8246
Epoch 6/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4726 - accuracy: 0.7852 - val_loss: 0.3948 - val_accuracy: 0.8596
Epoch 7/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4671 - accuracy: 0.8066 - val_loss: 0.3978 - val_accuracy: 0.8246
Epoch 8/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4695 - accuracy: 0.7832 - val_loss: 0.3901 - val_accuracy: 0.8421
Epoch 9/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4620 - accuracy: 0.8105 - val_loss: 0.3838 - val_accuracy: 0.8421
Epoch 10/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4634 - accuracy: 0.8066 - val_loss: 0.3909 - val_accuracy: 0.8246
Epoch 11/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4518 - accuracy: 0.8125 - val_loss: 0.3807 - val_accuracy: 0.8421
Epoch 12/200
52/52 [==============================] - 0s 3ms/step - loss: 0.4541 - accuracy: 0.8145 - val_loss: 0.3968 - val_accuracy: 0.7719
Epoch 13/200
52/52 [==============================] - 0s 3ms/step - loss: 0.4438 - accuracy: 0.8203 - val_loss: 0.3899 - val_accuracy: 0.7895
Epoch 14/200
52/52 [==============================] - 0s 4ms/step - loss: 0.4618 - accuracy: 0.8008 - val_loss: 0.4003 - val_accuracy: 0.7895
Epoch 15/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4474 - accuracy: 0.8164 - val_loss: 0.3935 - val_accuracy: 0.8070
Epoch 16/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4370 - accuracy: 0.8203 - val_loss: 0.3898 - val_accuracy: 0.8070
Epoch 17/200
52/52 [==============================] - 0s 3ms/step - loss: 0.4250 - accuracy: 0.8164 - val_loss: 0.3796 - val_accuracy: 0.8070
Epoch 18/200
52/52 [==============================] - 0s 3ms/step - loss: 0.4363 - accuracy: 0.8203 - val_loss: 0.3751 - val_accuracy: 0.8421
Epoch 19/200
52/52 [==============================] - 0s 3ms/step - loss: 0.4405 - accuracy: 0.8086 - val_loss: 0.3886 - val_accuracy: 0.8070
Epoch 20/200
52/52 [==============================] - 0s 5ms/step - loss: 0.4197 - accuracy: 0.8242 - val_loss: 0.3889 - val_accuracy: 0.8070
Epoch 21/200
52/52 [==============================] - 0s 3ms/step - loss: 0.4322 - accuracy: 0.8320 - val_loss: 0.3786 - val_accuracy: 0.8596
Epoch 22/200
52/52 [==============================] - 0s 3ms/step - loss: 0.4362 - accuracy: 0.8164 - val_loss: 0.3740 - val_accuracy: 0.8596
Epoch 23/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4357 - accuracy: 0.8262 - val_loss: 0.3807 - val_accuracy: 0.8246
Epoch 24/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4302 - accuracy: 0.8184 - val_loss: 0.3837 - val_accuracy: 0.8070
Epoch 25/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4299 - accuracy: 0.8164 - val_loss: 0.3721 - val_accuracy: 0.8246
Epoch 26/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4228 - accuracy: 0.8262 - val_loss: 0.3690 - val_accuracy: 0.8246
Epoch 27/200
52/52 [==============================] - 0s 4ms/step - loss: 0.4371 - accuracy: 0.8125 - val_loss: 0.3876 - val_accuracy: 0.8070
Epoch 28/200
52/52 [==============================] - 0s 4ms/step - loss: 0.4269 - accuracy: 0.8125 - val_loss: 0.3717 - val_accuracy: 0.8421
Epoch 29/200
52/52 [==============================] - 0s 3ms/step - loss: 0.4154 - accuracy: 0.8379 - val_loss: 0.3758 - val_accuracy: 0.8070
Epoch 30/200
52/52 [==============================] - 0s 3ms/step - loss: 0.4210 - accuracy: 0.8203 - val_loss: 0.3713 - val_accuracy: 0.8070
Epoch 31/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4252 - accuracy: 0.8281 - val_loss: 0.3813 - val_accuracy: 0.8070
Epoch 32/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4157 - accuracy: 0.8320 - val_loss: 0.3826 - val_accuracy: 0.8246
Epoch 33/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4178 - accuracy: 0.8164 - val_loss: 0.3737 - val_accuracy: 0.8246
Epoch 34/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4152 - accuracy: 0.8223 - val_loss: 0.3693 - val_accuracy: 0.8246
Epoch 35/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4195 - accuracy: 0.8223 - val_loss: 0.3726 - val_accuracy: 0.8246
Epoch 36/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4280 - accuracy: 0.8262 - val_loss: 0.3711 - val_accuracy: 0.8246
Epoch 37/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4100 - accuracy: 0.8340 - val_loss: 0.3697 - val_accuracy: 0.8246
Epoch 38/200
52/52 [==============================] - 0s 3ms/step - loss: 0.4167 - accuracy: 0.8145 - val_loss: 0.3557 - val_accuracy: 0.8772
Epoch 39/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4183 - accuracy: 0.8223 - val_loss: 0.3638 - val_accuracy: 0.8421
Epoch 40/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4300 - accuracy: 0.8203 - val_loss: 0.3533 - val_accuracy: 0.8772
Epoch 41/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4222 - accuracy: 0.8262 - val_loss: 0.3640 - val_accuracy: 0.8421
Epoch 42/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4120 - accuracy: 0.8164 - val_loss: 0.3561 - val_accuracy: 0.8596
Epoch 43/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4047 - accuracy: 0.8398 - val_loss: 0.3553 - val_accuracy: 0.8421
Epoch 44/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4040 - accuracy: 0.8203 - val_loss: 0.3687 - val_accuracy: 0.8246
Epoch 45/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4057 - accuracy: 0.8340 - val_loss: 0.3486 - val_accuracy: 0.8772
Epoch 46/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4003 - accuracy: 0.8340 - val_loss: 0.3443 - val_accuracy: 0.8421
Epoch 47/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4010 - accuracy: 0.8340 - val_loss: 0.3537 - val_accuracy: 0.8596
Epoch 48/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3996 - accuracy: 0.8320 - val_loss: 0.3532 - val_accuracy: 0.8596
Epoch 49/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4048 - accuracy: 0.8320 - val_loss: 0.3515 - val_accuracy: 0.8596
Epoch 50/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4047 - accuracy: 0.8340 - val_loss: 0.3465 - val_accuracy: 0.8596
Epoch 51/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3960 - accuracy: 0.8438 - val_loss: 0.3357 - val_accuracy: 0.8772
Epoch 52/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4047 - accuracy: 0.8320 - val_loss: 0.3410 - val_accuracy: 0.8772
Epoch 53/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3987 - accuracy: 0.8320 - val_loss: 0.3446 - val_accuracy: 0.8772
Epoch 54/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4172 - accuracy: 0.8262 - val_loss: 0.3485 - val_accuracy: 0.8772
Epoch 55/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3975 - accuracy: 0.8340 - val_loss: 0.3482 - val_accuracy: 0.8421
Epoch 56/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4033 - accuracy: 0.8340 - val_loss: 0.3427 - val_accuracy: 0.8596
Epoch 57/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3954 - accuracy: 0.8301 - val_loss: 0.3534 - val_accuracy: 0.8596
Epoch 58/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3827 - accuracy: 0.8438 - val_loss: 0.3377 - val_accuracy: 0.8772
Epoch 59/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3856 - accuracy: 0.8379 - val_loss: 0.3417 - val_accuracy: 0.8772
Epoch 60/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3965 - accuracy: 0.8340 - val_loss: 0.3409 - val_accuracy: 0.8772
Epoch 61/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3899 - accuracy: 0.8496 - val_loss: 0.3332 - val_accuracy: 0.8596
Epoch 62/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3975 - accuracy: 0.8359 - val_loss: 0.3350 - val_accuracy: 0.8772
Epoch 63/200
52/52 [==============================] - 0s 2ms/step - loss: 0.4013 - accuracy: 0.8262 - val_loss: 0.3363 - val_accuracy: 0.8596
Epoch 64/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3887 - accuracy: 0.8477 - val_loss: 0.3334 - val_accuracy: 0.8772
Epoch 65/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3906 - accuracy: 0.8457 - val_loss: 0.3326 - val_accuracy: 0.8596
Epoch 66/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3845 - accuracy: 0.8320 - val_loss: 0.3268 - val_accuracy: 0.8596
Epoch 67/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3931 - accuracy: 0.8320 - val_loss: 0.3460 - val_accuracy: 0.8421
Epoch 68/200
52/52 [==============================] - 0s 3ms/step - loss: 0.3720 - accuracy: 0.8438 - val_loss: 0.3381 - val_accuracy: 0.8421
Epoch 69/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3816 - accuracy: 0.8359 - val_loss: 0.3321 - val_accuracy: 0.8596
Epoch 70/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3789 - accuracy: 0.8320 - val_loss: 0.3271 - val_accuracy: 0.8596
Epoch 71/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3720 - accuracy: 0.8438 - val_loss: 0.3205 - val_accuracy: 0.8596
Epoch 72/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3834 - accuracy: 0.8301 - val_loss: 0.3341 - val_accuracy: 0.8596
Epoch 73/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3849 - accuracy: 0.8340 - val_loss: 0.3278 - val_accuracy: 0.8596
Epoch 74/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3781 - accuracy: 0.8359 - val_loss: 0.3342 - val_accuracy: 0.8246
Epoch 75/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3815 - accuracy: 0.8398 - val_loss: 0.3243 - val_accuracy: 0.8246
Epoch 76/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3773 - accuracy: 0.8457 - val_loss: 0.3345 - val_accuracy: 0.8246
Epoch 77/200
52/52 [==============================] - 0s 3ms/step - loss: 0.3872 - accuracy: 0.8301 - val_loss: 0.3398 - val_accuracy: 0.8596
Epoch 78/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3683 - accuracy: 0.8477 - val_loss: 0.3306 - val_accuracy: 0.8421
Epoch 79/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3824 - accuracy: 0.8398 - val_loss: 0.3291 - val_accuracy: 0.8246
Epoch 80/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3785 - accuracy: 0.8281 - val_loss: 0.3194 - val_accuracy: 0.8421
Epoch 81/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3674 - accuracy: 0.8438 - val_loss: 0.3248 - val_accuracy: 0.8421
Epoch 82/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3675 - accuracy: 0.8398 - val_loss: 0.3253 - val_accuracy: 0.8596
Epoch 83/200
52/52 [==============================] - 0s 4ms/step - loss: 0.3811 - accuracy: 0.8340 - val_loss: 0.3297 - val_accuracy: 0.8421
Epoch 84/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3838 - accuracy: 0.8281 - val_loss: 0.3198 - val_accuracy: 0.8596
Epoch 85/200
52/52 [==============================] - 0s 3ms/step - loss: 0.3746 - accuracy: 0.8457 - val_loss: 0.3291 - val_accuracy: 0.8421
Epoch 86/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3712 - accuracy: 0.8477 - val_loss: 0.3245 - val_accuracy: 0.8421
Epoch 87/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3794 - accuracy: 0.8340 - val_loss: 0.3208 - val_accuracy: 0.8421
Epoch 88/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3815 - accuracy: 0.8340 - val_loss: 0.3279 - val_accuracy: 0.8421
Epoch 89/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3773 - accuracy: 0.8379 - val_loss: 0.3287 - val_accuracy: 0.8421
Epoch 90/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3727 - accuracy: 0.8379 - val_loss: 0.3224 - val_accuracy: 0.8421
Epoch 91/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3751 - accuracy: 0.8359 - val_loss: 0.3170 - val_accuracy: 0.8421
Epoch 92/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3840 - accuracy: 0.8340 - val_loss: 0.3231 - val_accuracy: 0.8421
Epoch 93/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3757 - accuracy: 0.8359 - val_loss: 0.3161 - val_accuracy: 0.8596
Epoch 94/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3824 - accuracy: 0.8379 - val_loss: 0.3250 - val_accuracy: 0.8772
Epoch 95/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3559 - accuracy: 0.8613 - val_loss: 0.3119 - val_accuracy: 0.8596
Epoch 96/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3614 - accuracy: 0.8438 - val_loss: 0.3107 - val_accuracy: 0.8596
Epoch 97/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3727 - accuracy: 0.8516 - val_loss: 0.3137 - val_accuracy: 0.8772
Epoch 98/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3735 - accuracy: 0.8496 - val_loss: 0.3161 - val_accuracy: 0.8421
Epoch 99/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3756 - accuracy: 0.8418 - val_loss: 0.3232 - val_accuracy: 0.8596
Epoch 100/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3766 - accuracy: 0.8457 - val_loss: 0.3220 - val_accuracy: 0.8421
Epoch 101/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3547 - accuracy: 0.8457 - val_loss: 0.3192 - val_accuracy: 0.8421
Epoch 102/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3640 - accuracy: 0.8535 - val_loss: 0.3094 - val_accuracy: 0.8596
Epoch 103/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3714 - accuracy: 0.8457 - val_loss: 0.3141 - val_accuracy: 0.8421
Epoch 104/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3787 - accuracy: 0.8418 - val_loss: 0.3074 - val_accuracy: 0.8596
Epoch 105/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3653 - accuracy: 0.8516 - val_loss: 0.3098 - val_accuracy: 0.8596
Epoch 106/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3625 - accuracy: 0.8477 - val_loss: 0.3088 - val_accuracy: 0.8421
Epoch 107/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3701 - accuracy: 0.8477 - val_loss: 0.3144 - val_accuracy: 0.8596
Epoch 108/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3661 - accuracy: 0.8496 - val_loss: 0.3111 - val_accuracy: 0.8421
Epoch 109/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3575 - accuracy: 0.8555 - val_loss: 0.3084 - val_accuracy: 0.8246
Epoch 110/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3543 - accuracy: 0.8438 - val_loss: 0.3164 - val_accuracy: 0.8421
Epoch 111/200
52/52 [==============================] - 0s 3ms/step - loss: 0.3766 - accuracy: 0.8379 - val_loss: 0.3128 - val_accuracy: 0.8421
Epoch 112/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3618 - accuracy: 0.8535 - val_loss: 0.3143 - val_accuracy: 0.8596
Epoch 113/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3520 - accuracy: 0.8594 - val_loss: 0.3129 - val_accuracy: 0.8596
Epoch 114/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3593 - accuracy: 0.8457 - val_loss: 0.3132 - val_accuracy: 0.8421
Epoch 115/200
52/52 [==============================] - 0s 3ms/step - loss: 0.3710 - accuracy: 0.8438 - val_loss: 0.3154 - val_accuracy: 0.8596
Epoch 116/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3729 - accuracy: 0.8379 - val_loss: 0.3121 - val_accuracy: 0.8596
Epoch 117/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3582 - accuracy: 0.8516 - val_loss: 0.3142 - val_accuracy: 0.8421
Epoch 118/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3689 - accuracy: 0.8457 - val_loss: 0.3169 - val_accuracy: 0.8246
Epoch 119/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3474 - accuracy: 0.8535 - val_loss: 0.3130 - val_accuracy: 0.8421
Epoch 120/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3586 - accuracy: 0.8496 - val_loss: 0.3121 - val_accuracy: 0.8246
Epoch 121/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3623 - accuracy: 0.8496 - val_loss: 0.3097 - val_accuracy: 0.8421
Epoch 122/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3668 - accuracy: 0.8516 - val_loss: 0.3080 - val_accuracy: 0.8421
Epoch 123/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3569 - accuracy: 0.8535 - val_loss: 0.3091 - val_accuracy: 0.8421
Epoch 124/200
52/52 [==============================] - 0s 3ms/step - loss: 0.3489 - accuracy: 0.8613 - val_loss: 0.3020 - val_accuracy: 0.8421
Epoch 125/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3578 - accuracy: 0.8418 - val_loss: 0.3055 - val_accuracy: 0.8421
Epoch 126/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3639 - accuracy: 0.8398 - val_loss: 0.3055 - val_accuracy: 0.8596
Epoch 127/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3596 - accuracy: 0.8496 - val_loss: 0.3050 - val_accuracy: 0.8421
Epoch 128/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3735 - accuracy: 0.8359 - val_loss: 0.2993 - val_accuracy: 0.8596
Epoch 129/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3585 - accuracy: 0.8516 - val_loss: 0.3009 - val_accuracy: 0.8596
Epoch 130/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3563 - accuracy: 0.8438 - val_loss: 0.2884 - val_accuracy: 0.8421
Epoch 131/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3634 - accuracy: 0.8438 - val_loss: 0.2980 - val_accuracy: 0.8596
Epoch 132/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3674 - accuracy: 0.8418 - val_loss: 0.3114 - val_accuracy: 0.8596
Epoch 133/200
52/52 [==============================] - 0s 5ms/step - loss: 0.3490 - accuracy: 0.8496 - val_loss: 0.3043 - val_accuracy: 0.8421
Epoch 134/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3484 - accuracy: 0.8672 - val_loss: 0.3018 - val_accuracy: 0.8246
Epoch 135/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3655 - accuracy: 0.8301 - val_loss: 0.3046 - val_accuracy: 0.8596
Epoch 136/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3521 - accuracy: 0.8594 - val_loss: 0.3034 - val_accuracy: 0.8246
Epoch 137/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3470 - accuracy: 0.8594 - val_loss: 0.3001 - val_accuracy: 0.8421
Epoch 138/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3541 - accuracy: 0.8457 - val_loss: 0.3021 - val_accuracy: 0.8421
Epoch 139/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3623 - accuracy: 0.8438 - val_loss: 0.2971 - val_accuracy: 0.8421
Epoch 140/200
52/52 [==============================] - 0s 2ms/step - loss: 0.3333 - accuracy: 0.8613 - val_loss: 0.3001 - val_accuracy: 0.8421
Epoch 141/200

In [123]:
# Ã‰valuation du modÃ¨le sur les donnÃ©es de test
test_loss, test_acc = model.evaluate(X_test, y_test)
print('Test accuracy:', test_acc)

5/5 [==============================] - 0s 3ms/step - loss: 0.5240 - accuracy: 0.7972
Test accuracy: 0.7972028255462646

In [ ]:
#On peut voir que nous sommes passÃ© de 0.61 Ã  0.79 grace aux fait de garder les colognes et les standardiser